### ISSUE TITLE
Libfuncs: consts

### ISSUE THREAD

**Issue by igaray** [lambdaclass/cairo_sierra_2_MLIR#23]
[Sierra implementation](https://github.com/starkware-libs/cairo/blob/main/crates/cairo-lang-sierra/src/extensions/modules/consts.rs)

The consts module in cairo-sierra-lang does not contain a particular libfunc but instead the `ConstGenLibfunc` trait, `WrapConstGenLibfunc` and `SignatureAndConstConcreteLibfunc` types. Explore how these are used in sierra and whether they need to be taken into account when translating sierra to MLIR.

**Comment by edg-l** [comment]
I think this is more a sierra implementation thing than something we can use when consuming the sierra code. We got the consts for all uX and felt types done i think
