### ISSUE TITLE
Libfuncs: enm

### ISSUE THREAD

**Issue by igaray** [lambdaclass/cairo_sierra_2_MLIR#26]
[Sierra implementation](https://github.com/starkware-libs/cairo/blob/main/crates/cairo-lang-sierra/src/extensions/modules/enm.rs)
- [x] enum_init
- [x] enum_match

The `enum_snapshot_match` libfunc is covered by #93

**Comment by edg-l** [comment]
https://mapping-high-level-constructs-to-llvm-ir.readthedocs.io/en/latest/basic-constructs/unions.html#tagged-unions
