### ISSUE TITLE
Libfuncs: uint

### ISSUE THREAD

**Issue by igaray** [lambdaclass/cairo_sierra_2_MLIR#58]
- [Sierra implementation for 8,16,32 and 64 bit widths](https://github.com/starkware-libs/cairo/blob/main/crates/cairo-lang-sierra/src/extensions/modules/uint.rs)
- [Sierra implementation for 128 bit width](https://github.com/starkware-libs/cairo/blob/main/crates/cairo-lang-sierra/src/extensions/modules/uint128.rs)
- Libfuncs for a given width:
    - [x] uN_const
    - [x] uN_eq `uN_eq(T, T) -> [branch, branch] (fallthrough 0)`
    - [x] uN_is_zero `uN_is_zero(T) -> [branch, branch] (fallthrough 0)`
    - [x] uN_le `uN_le(RangeCheckPtr, T, T) -> [branch, branch] (fallthrough 0)`
    - [x] uN_lt `uN_lt(RangeCheckPtr, T, T) -> [branch, branch] (fallthrough 0)`
    - [x] uN_overflowing_add `_overflowing_add(RangeCheckPtr, T, T) -> [branch(RangeCheckPtr, T), branch(RangeCheckPtr, T)]`
    - [x] uN_overflowing_sub `_overflowing_sub(RangeCheckPtr, T, T) -> [branch(RangeCheckPtr, T), branch(RangeCheckPtr, T)]`
    - [x] uN_safe_divmod
    - [x] uN_to_felt252
    - [x] uN_try_from_felt252
    - [x] uN_wide_mul

**Comment by DomHenderson** [comment]
#84 includes all uN_is_zero

**Comment by igaray** [comment]
Moving uN_sqrt (Experimental) out to #133
